var koa = require('koa')
var proxy=require('koa-proxy')
var route=require('koa-route')
var mongo=require('koa-mongo')
var app = koa()
app.use(mongo({host:process.env.host||'localhost',port:process.env.port||27018,db:"main"}))
app.use(route.get("/admin/*",function*(){
	this.body=yield this.mongo.collection("users").find().toArray()
}))
app.use(proxy({host:"http://localhost:8080"}))
app.listen(80)
