node:
  image: daocloud.io/qq08420/fuzhuang:master-e40517b
  restart: always
  links:
  - mongo
  ports:
  - '80'
  environment:
  - VIRTUAL_HOST=www.*,a.*
mongo:
  image: library/mongo:3.2.4
  restart: always
  ports:
  - '27017'
proxy:
  image: daocloud.io/qq08420/nginx-proxy:master-init
  privileged: true
  restart: always
  ports:
  - 443:443
  - 80:80
  volumes:
  - /root/cache.conf:/etc/nginx/conf.d/cache.conf
  - /var/run/docker.sock:/tmp/docker.sock